language: python
python:
  - "3.6"

# Set up dependencies
install:
  - make install

# Run coverage tests
script:
  - make test
  - make complexity

# Print coverage report to coveralls.io
after_success:
  - coveralls
